### ISSUE TITLE
How to Increase Text size !

### ISSUE THREAD

**Issue by solrac3f** [bonezegei/Bonezegei_SSD1306#1]
Hello,
 Good Job with this Library.
Is it possible to increase the text size or implement other fonts?

**Comment by bonezegei** [comment]
Good day,

Sorry for the late response, currently there is no function to increase text size. But I have just updated the Library for new fonts size. Arial8, Arial10, Arial12, Arial14 see FontDemo Example. The Library might take effect after 2 hours. Thank you for pointing this issue out. I might as well update several fonts later.

**Comment by solrac3f** [comment]
Hello,Thank you for your prompt response and for implementing new font sizes in the library. Looking forward to trying out the new fonts.
