### ISSUE TITLE
The @ and the W in arial14 are broken

### ISSUE THREAD

**Issue by maarten-pennings** [bonezegei/Bonezegei_SSD1306#3]
The @ and the W in arial14 are broken.

```C++
  oled.drawText(0, 0, "AA@BBWCC", 1, arial_14ptBitmaps, arial_14ptDescriptors);
```

I suspect that is because those are the only characters that are three bytes wide in the bitmap.
My guess is that the if here needs _three_ cases 0..7, 7..15 and 15..23, not two.

```
  if (dsc[b][0] <= 8) {
    for (int a = 0; a < dsc[b][1]; a++) {
      _setChar8(xRun, yRun + a, fd[(dsc[b][2] + a)], dsc[b][0], color);
    }
  } else {
    for (int a = 0; a < (dsc[b][1] * 2); a++) {
      if ((a % 2) == 0) _setChar8(xRun, yRun + (a / 2), fd[(dsc[b][2] + a)], 8, color);
      else _setChar8(xRun + 8, yRun + (a / 2), fd[(dsc[b][2] + a)], dsc[b][0] - 7, color);
    }
  }
```

**Comment by bonezegei** [comment]
Thank you for the valuable insights and for highlighting the issue with the code. Your input is greatly appreciated, and it's clear that addressing this problem will enhance the project's functionality. I plan to allocate time to resolve this in the upcoming days. Once again, thank you for your contribution to improving the quality of my work.

**Comment by maarten-pennings** [comment]
Glad I could help. 

Could you add an example for

```c++
void drawText(int x, int y, const char *str, Bonezegei_Font fnt);
```

and also explain the difference with 

```c++
void drawText(int x, int y, const char *str, uint8_t color, const char fd[], const int dsc[95][3]);
```

**Comment by maarten-pennings** [comment]
One more question. You picked GPL license, which makes it impossible for me to use your work (I would be forced to open up _all_ of mine which I can't). 

Is GPL a deliberate choice or would you be willing to relax the license to your library to say MIT?

**Comment by maarten-pennings** [comment]
This might be a more general way to map font bmp data to pixels.
More general because it loops over the character width.

```c++
  // Lookup bitmap in font
  int width = ... from font descriptor... ;
  int height = ... from font descriptor... ;
  const uint8_t * bmp = ... from font descriptor... ;
  // Draw character, pixel by pixel
  int stride= (width-1)/8+1; // ceil(width/8) is width of the char in bytes
  for( int y=0; y<height; y++ ) {
    for( int x=0; x<width; x++ ) {
      int ix = y*stride + x/8;
      int mask = 1<<(7-x%8);
      int draw = bmp[ix] & mask;
      //Serial.printf("%d", draw!=0 );
      if( draw ) drawPixel(cursor_x+x, cursor_y+y, col)
    }
    //Serial.printf("\n");
  }
```

**Comment by bonezegei** [comment]
Good day [maarten-pennings](https://github.com/maarten-pennings)

I have already updated the code yesterday for quick fix for the characters 3 byte wide characters. Maybe any day this week i will add functions for drawing bitmap images. Thank you again for great insights.

**Comment by maarten-pennings** [comment]
Sorry didn't see that. You're quick, thanks. 

Please feel free to close this issue if you've solved it.
